In [1]:
import pandas as pd

In [2]:
df_fake=pd.read_csv("Fake.csv")

In [3]:
df_fake

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"
...,...,...,...,...
23476,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,Middle-east,"January 16, 2016"
23477,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,Middle-east,"January 16, 2016"
23478,Sunnistan: US and Allied ‘Safe Zone’ Plan to T...,Patrick Henningsen 21st Century WireRemember ...,Middle-east,"January 15, 2016"
23479,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,Middle-east,"January 14, 2016"
23480,10 U.S. Navy Sailors Held by Iranian Military ...,21st Century Wire says As 21WIRE predicted in ...,Middle-east,"January 12, 2016"

In [4]:
df_fake['target']='fake'

In [5]:
df_fake

,title,text,subject,date,target
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",fake
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",fake
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",fake
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",fake
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",fake
...,...,...,...,...,...
23476,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,Middle-east,"January 16, 2016",fake
23477,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,Middle-east,"January 16, 2016",fake
23478,Sunnistan: US and Allied ‘Safe Zone’ Plan to T...,Patrick Henningsen 21st Century WireRemember ...,Middle-east,"January 15, 2016",fake
23479,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,Middle-east,"January 14, 2016",fake
23480,10 U.S. Navy Sailors Held by Iranian Military ...,21st Century Wire says As 21WIRE predicted in ...,Middle-east,"January 12, 2016",fake

In [6]:
df_real=pd.read_csv("True.csv")

In [7]:
df_real

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"
...,...,...,...,...
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017"
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017"
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017"
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017"
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017"

In [8]:
df_real['target']='real'

In [9]:
df_real

,title,text,subject,date,target
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",real
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",real
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",real
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",real
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",real
...,...,...,...,...,...
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017",real
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017",real
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017",real
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017",real
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017",real

In [10]:
import pandas as pd

df = pd.concat([df_real, df_fake], axis=0, ignore_index=True)

In [11]:
df

,title,text,subject,date,target
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",real
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",real
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",real
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",real
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",real
...,...,...,...,...,...
44893,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,Middle-east,"January 16, 2016",fake
44894,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,Middle-east,"January 16, 2016",fake
44895,Sunnistan: US and Allied ‘Safe Zone’ Plan to T...,Patrick Henningsen 21st Century WireRemember ...,Middle-east,"January 15, 2016",fake
44896,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,Middle-east,"January 14, 2016",fake
44897,10 U.S. Navy Sailors Held by Iranian Military ...,21st Century Wire says As 21WIRE predicted in ...,Middle-east,"January 12, 2016",fake

In [12]:
import pandas as pd

# assume dataframe name is df
X = df["text"].astype(str)
y = df["target"].map({"real": 1, "fake": 0})

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

model = Pipeline([
    ("tfidf", TfidfVectorizer(
        stop_words="english",
        max_df=0.7,
        ngram_range=(1,2)
    )),
    ("clf", LogisticRegression(max_iter=1000))
])

model.fit(X_train, y_train)

Pipeline(steps=[('tfidf',
                 TfidfVectorizer(max_df=0.7, ngram_range=(1, 2),
                                 stop_words='english')),
                ('clf', LogisticRegression(max_iter=1000))])

In [15]:
from sklearn.metrics import accuracy_score, classification_report

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred, target_names=["fake", "real"]))

Accuracy: 0.9854120267260579
              precision    recall  f1-score   support

        fake       0.99      0.98      0.99      4696
        real       0.98      0.99      0.98      4284

    accuracy                           0.99      8980
   macro avg       0.99      0.99      0.99      8980
weighted avg       0.99      0.99      0.99      8980

In [16]:
sample_text = """The government announced a new policy today regarding taxation."""
prediction = model.predict([sample_text])[0]

print("Prediction:", "REAL" if prediction == 1 else "FAKE")

Prediction: FAKE

# LLM

In [17]:
import requests

SERPER_URL = "https://google.serper.dev/news"

def fetch_news_text(topic, num_results=5):
    headers = {
        "X-API-KEY": "3cd9effd78d88fd5ac0b20a280f2a58e2c2a10c6",
        "Content-Type": "application/json"
    }

    payload = {
        "q": topic,
        "num": num_results
    }

    response = requests.post(SERPER_URL, headers=headers, json=payload)
    response.raise_for_status()
    data = response.json()

    results = []
    for item in data.get("news", []):
        result = {
            "title": item.get("title", ""),
            "snippet": item.get("snippet", ""),
            "url": item.get("link", "")
        }
        results.append(result)

    return results

In [18]:
fetch_news_text("US election interference 2024",5)

[{'title': 'Secret US cyber operations shielded 2024 election from foreign trolls, but now the Trump admin has gutted protections',
  'snippet': 'Weeks before the 2024 election, American military hackers carried out a secret operation to disrupt the work of Russian trolls spewing false...',
  'url': 'https://www.cnn.com/2026/01/28/politics/hacking-disinformation-election-security'},
 {'title': 'The Trump Administration’s Campaign to Undermine the Next Election',
  'snippet': 'In 2020, 2022, and 2024, our nation held federal elections. Despite the pandemic, threats of violence, denial of results, and extraordinary...',
  'url': 'https://www.brennancenter.org/our-work/research-reports/trump-administrations-campaign-undermine-next-election'},
 {'title': 'A Lesson in Resilience: Moldova’s Resistance to Election Interference',
  'snippet': '“Our vulnerabilities are being weaponized by foreign powers — amplified by technology and artificial intelligence, financed through...',
  'url': 'https://www.ifes.org/publications/lesson-resilience-moldovas-resistance-election-interference'},
 {'title': 'Fulton County election interference case against Trump and his allies is dismissed',
  'snippet': "Judge Scott McAfee's dismissal marks the end of the last criminal case facing Trump related to that year's election.",
  'url': 'https://georgiarecorder.com/2025/11/26/fulton-county-election-interference-case-against-trump-and-his-allies-is-dismissed/'},
 {'title': 'Foreign Election Interference Threat Looms Ahead of the 2024 Presidential Election',
  'snippet': 'Foreign Election Interference Threat Looms Ahead of the 2024 Presidential Election ... Just weeks before the 2024 election, the Justice...',
  'url': 'https://www.irinsider.org/north-america-2/k64fs2cycfdattt-jc89j-dfkae-6y89r-pgppy-ae4ec-s9l7n-9aeyz'},
 {'title': "Trump's 2024 Victory Under Scrutiny as Legal Complaints Target Elon Musk's Election Tactics",
  'snippet': 'A Wisconsin nonprofit has filed a complaint against Elon Musk and his political allies, alleging violations of state election law in the...',
  'url': 'https://www.washingtoninformer.com/wisconsin-complaint-accuses-musk-election-interference/'},
 {'title': "Ex-CIA analyst challenges Trump's attempt to discredit Russian election interference probe",
  'snippet': 'The Trump administration is trying to discredit the intelligence assessment that concluded Russian President Putin ordered a campaign to...',
  'url': 'https://www.pbs.org/newshour/show/ex-cia-analyst-challenges-trumps-attempt-to-discredit-russian-election-interference-probe'},
 {'title': 'The future of democracy: lessons from the US fight against foreign electoral interference in 2024',
  'snippet': 'The US Department of Justice announced a set of measures to curb electoral interference in the upcoming presidential election, scheduled to take place two...',
  'url': 'https://www.iss.europa.eu/publications/briefs/future-democracy-lessons-us-fight-against-foreign-electoral-interference-2024'},
 {'title': 'US House Judiciary Committee alleges EU interference in eight national elections',
  'snippet': 'The US House Judiciary Committee has released a report alleging that European Union institutions interfered in at least eight national...',
  'url': 'https://www.azernews.az/region/254164.html'},
 {'title': 'Romania’s 2024–2025 Presidential Election Crisis and Its Aftermath',
  'snippet': "Romania's most recent presidential election marked the most severe electoral disruption in the country's post-communist history.",
  'url': 'https://www.iiea.com/blog/romanias-20242025-presidential-election-crisis-and-its-aftermath'}]

In [19]:
def predict_topic(topic):
    news_items = fetch_news_text(topic)
    results = []

    for item in news_items:
        text = f"{item['title']} {item['snippet']}".strip()
        pred = model.predict([text])[0]
        label = "REAL" if pred == 1 else "FAKE"

        results.append({
            "title": item["title"],
            "snippet": item["snippet"],
            "url": item["url"],
            "prediction": label
        })

    return results

In [20]:
topic = "us attacks venezuela"

predictions = predict_topic(topic)

for i, p in enumerate(predictions, 1):
    print(f"\nArticle {i}")
    print("Prediction:", p["prediction"])
    print("Title:", p["title"])
    print("Snippet:", p["snippet"][:300])
    print("URL:", p["url"])

Article 1
Prediction: FAKE
Title: The ‘discombobulator’: Did US use ‘secret weapon’ in Maduro abduction?
Snippet: US President Donald Trump refers to a 'sonic weapon' he describes as a 'discombobulator', but what is he talking about?
URL: https://www.aljazeera.com/features/2026/1/26/the-discombobulator-did-us-use-secret-weapon-in-maduro-abduction

Article 2
Prediction: FAKE
Title: Families sue US over deadly boat strike off Venezuela coast
Snippet: Families sue US over deadly boat strike off Venezuela coast ... The families of two Trinidadian men killed in a US strike on an alleged drug-...
URL: https://www.bbc.com/news/articles/c98jr75w4zko

Article 3
Prediction: FAKE
Title: What’s Happening With the U.S. and Venezuela, Explained
Snippet: It's been a whirlwind year for Venezuela, and it's just getting started. Over the weekend, the U.S. launched an incursion into Caracas,...
URL: https://time.com/7344628/us-venezuela-trump-maduro-oil-drugs-war-explainer-questions-answered/

Article 4
Prediction: REAL
Title: A CIA team, steel doors and a fateful phone call: How the U.S. captured Maduro in Venezuela
Snippet: President Donald Trump approved the strike before Christmas after months of planning, including troops training using a model of Maduro's...
URL: https://www.nbcnews.com/politics/donald-trump/us-venezuela-strike-nicolas-maduro-captured-how-timeline-trump-rcna252041

Article 5
Prediction: REAL
Title: A timeline of U.S. military escalation against Venezuela leading to Maduro's capture
Snippet: On Saturday, the U.S. conducted a “large-scale strike” against Venezuela. Before the escalation, there had been 35 known strikes against...
URL: https://www.pbs.org/newshour/world/a-timeline-of-u-s-military-escalation-against-venezuela-leading-to-maduros-capture

Article 6
Prediction: FAKE
Title: Russia’s Fearsome Arsenal Fizzled in Venezuela. Here’s Why.
Snippet: Venezuela's advanced, Russian-made air defense systems were not even hooked up to radar when U.S. helicopters swooped in to snatch President...
URL: https://www.nytimes.com/2026/01/12/world/americas/venezuela-russian-weapons-fail.html

Article 7
Prediction: FAKE
Title: Making sense of the US military operation in Venezuela
Snippet: On January 3, 2026, the United States launched a special operation to exfiltrate Venezuelan President Nicolás Maduro and his wife from...
URL: https://www.brookings.edu/articles/making-sense-of-the-us-military-operation-in-venezuela/

Article 8
Prediction: REAL
Title: Ousted Venezuelan President Maduro arraigned in U.S. court; Trump threatens other nations
Snippet: Ousted Venezuelan President Nicolás Maduro and his wife appeared before a judge in New York to face charges related to drug trafficking...
URL: https://www.cbsnews.com/live-updates/venezuela-trump-maduro-charges/

Article 9
Prediction: FAKE
Title: Trump says U.S. will run Venezuela after U.S. captures Maduro
Snippet: Summary. US captured Venezuelan leader Maduro; Trump says US to run Venezuela until a 'safe, proper and judicious transition', U.S. oil...
URL: https://www.reuters.com/world/americas/loud-noises-heard-venezuela-capital-southern-area-without-electricity-2026-01-03/

Article 10
Prediction: FAKE
Title: Imagery from Venezuela Shows a Surgical Strike, Not Shock and Awe
Snippet: CSIS experts analyze new satellite imagery of U.S. strikes against Venezuela carried out during the mission to capture Nicolás Maduro.
URL: https://www.csis.org/analysis/imagery-venezuela-shows-surgical-strike-not-shock-and-awe

In [21]:
df1=pd.read_csv("all_sentences.csv")

In [22]:
df1

,Sentence_id,Text,Speaker,Speaker_title,Speaker_party,Speaker_role,File_id,Length,Line_number,Sentiment
0,1,"September 25, 1988",Information,NaN,NaN,NaN,1988-09-25.txt,3,1,NaN
1,2,The First Bush-Dukakis Presidential Debate,Information,NaN,NaN,NaN,1988-09-25.txt,5,2,0.000000
2,3,Good evening.,Jim Lehrer,NaN,NaN,Moderator,1988-09-25.txt,2,3,0.343189
3,4,On behalf of the Commission on Presidential De...,Jim Lehrer,NaN,NaN,Moderator,1988-09-25.txt,23,4,0.810043
4,5,I'm Jim Lehrer of the McNeil-Lehrer News Hour.,Jim Lehrer,NaN,NaN,Moderator,1988-09-25.txt,8,5,0.000000
...,...,...,...,...,...,...,...,...,...,...
32067,34465,Now the decision is up to you.,Chris Wallace,"Correspondent, Fox News",NaN,Moderator,2016-10-19.txt,7,1344,0.000000
32068,34466,"While millions have already voted, Election Da...",Chris Wallace,"Correspondent, Fox News",NaN,Moderator,2016-10-19.txt,14,1345,0.000000
32069,34467,One thing everyone here can agree on: We hope ...,Chris Wallace,"Correspondent, Fox News",NaN,Moderator,2016-10-19.txt,13,1346,0.659700
32070,34468,It is one of the honors and obligations of liv...,Chris Wallace,"Correspondent, Fox News",NaN,Moderator,2016-10-19.txt,14,1347,0.847200
32071,34469,"Thank you, and good night.",Chris Wallace,"Correspondent, Fox News",NaN,Moderator,2016-10-19.txt,5,1348,0.659700

In [23]:
df2=pd.read_csv("crowdsourced.csv")

In [24]:
df2

,Sentence_id,Text,Speaker,Speaker_title,Speaker_party,File_id,Length,Line_number,Sentiment,Verdict
0,16,I think we've seen a deterioration of values.,George Bush,Vice President,REPUBLICAN,1988-09-25.txt,8,16,0.000000,-1
1,17,I think for a while as a nation we condoned th...,George Bush,Vice President,REPUBLICAN,1988-09-25.txt,16,17,-0.456018,-1
2,18,"For a while, as I recall, it even seems to me ...",George Bush,Vice President,REPUBLICAN,1988-09-25.txt,29,18,-0.805547,-1
3,19,"So we've seen a deterioration in values, and o...",George Bush,Vice President,REPUBLICAN,1988-09-25.txt,35,19,0.698942,-1
4,20,"We got away, we got into this feeling that val...",George Bush,Vice President,REPUBLICAN,1988-09-25.txt,15,20,0.000000,-1
...,...,...,...,...,...,...,...,...,...,...
22496,34452,You get shot walking to the store.,Donald Trump,Businessman,REPUBLICAN,2016-10-19.txt,7,1331,0.000000,0
22497,34455,I will do more for African-Americans and Latin...,Donald Trump,Businessman,REPUBLICAN,2016-10-19.txt,16,1334,0.000000,-1
22498,34456,All she's done is talk to the African-American...,Donald Trump,Businessman,REPUBLICAN,2016-10-19.txt,30,1335,0.000000,-1
22499,34457,"We are going to make America strong again, and...",Donald Trump,Businessman,REPUBLICAN,2016-10-19.txt,23,1336,0.812600,-1
22500,34458,We cannot take four more years of Barack Obama...,Donald Trump,Businessman,REPUBLICAN,2016-10-19.txt,19,1337,0.000000,-1

In [25]:
df3=pd.read_csv("groundtruth.csv")

In [26]:
df3

,Sentence_id,Text,Speaker,Speaker_title,Speaker_party,File_id,Length,Line_number,Sentiment,Verdict
0,26,"You know, I saw a movie - ""Crocodile Dundee.""",George Bush,Vice President,REPUBLICAN,1988-09-25.txt,9,26,0.000000,0
1,80,We're consuming 50 percent of the world's coca...,Michael Dukakis,Governor,DEMOCRAT,1988-09-25.txt,8,80,-0.740979,1
2,129,That answer was about as clear as Boston harbor.,George Bush,Vice President,REPUBLICAN,1988-09-25.txt,9,129,0.000000,-1
3,131,Let me help the governor.,George Bush,Vice President,REPUBLICAN,1988-09-25.txt,5,131,0.212987,-1
4,172,We've run up more debt in the last eight years...,Michael Dukakis,Governor,DEMOCRAT,1988-09-25.txt,22,172,-0.268506,1
...,...,...,...,...,...,...,...,...,...,...
1027,28958,He has promised a trillion dollars out of the ...,Al Gore,Vice President,DEMOCRAT,2000-10-17.txt,24,953,0.363438,1
1028,28965,(LAUGHTER) I -- there's an old high school deb...,George W. Bush,Governor,REPUBLICAN,2000-10-17.txt,23,960,-0.679982,-1
1029,29011,"Well, can I answer that?",George W. Bush,Governor,REPUBLICAN,2000-10-17.txt,5,1006,0.413020,-1
1030,29060,I look forward to the final weeks of this camp...,George W. Bush,Governor,REPUBLICAN,2000-10-17.txt,10,1055,0.625957,-1
1031,29062,"For those of you for me, thanks for your help.",George W. Bush,Governor,REPUBLICAN,2000-10-17.txt,10,1057,0.844495,-1

In [27]:
import pandas as pd

df_stacked = pd.concat([df2, df3], axis=0, ignore_index=True)

In [28]:
df_stacked

,Sentence_id,Text,Speaker,Speaker_title,Speaker_party,File_id,Length,Line_number,Sentiment,Verdict
0,16,I think we've seen a deterioration of values.,George Bush,Vice President,REPUBLICAN,1988-09-25.txt,8,16,0.000000,-1
1,17,I think for a while as a nation we condoned th...,George Bush,Vice President,REPUBLICAN,1988-09-25.txt,16,17,-0.456018,-1
2,18,"For a while, as I recall, it even seems to me ...",George Bush,Vice President,REPUBLICAN,1988-09-25.txt,29,18,-0.805547,-1
3,19,"So we've seen a deterioration in values, and o...",George Bush,Vice President,REPUBLICAN,1988-09-25.txt,35,19,0.698942,-1
4,20,"We got away, we got into this feeling that val...",George Bush,Vice President,REPUBLICAN,1988-09-25.txt,15,20,0.000000,-1
...,...,...,...,...,...,...,...,...,...,...
23528,28958,He has promised a trillion dollars out of the ...,Al Gore,Vice President,DEMOCRAT,2000-10-17.txt,24,953,0.363438,1
23529,28965,(LAUGHTER) I -- there's an old high school deb...,George W. Bush,Governor,REPUBLICAN,2000-10-17.txt,23,960,-0.679982,-1
23530,29011,"Well, can I answer that?",George W. Bush,Governor,REPUBLICAN,2000-10-17.txt,5,1006,0.413020,-1
23531,29060,I look forward to the final weeks of this camp...,George W. Bush,Governor,REPUBLICAN,2000-10-17.txt,10,1055,0.625957,-1
23532,29062,"For those of you for me, thanks for your help.",George W. Bush,Governor,REPUBLICAN,2000-10-17.txt,10,1057,0.844495,-1

In [29]:
final_df=df_stacked.drop(["Sentence_id","File_id","Length","Line_number"],axis=1)

In [30]:
final_df

,Text,Speaker,Speaker_title,Speaker_party,Sentiment,Verdict
0,I think we've seen a deterioration of values.,George Bush,Vice President,REPUBLICAN,0.000000,-1
1,I think for a while as a nation we condoned th...,George Bush,Vice President,REPUBLICAN,-0.456018,-1
2,"For a while, as I recall, it even seems to me ...",George Bush,Vice President,REPUBLICAN,-0.805547,-1
3,"So we've seen a deterioration in values, and o...",George Bush,Vice President,REPUBLICAN,0.698942,-1
4,"We got away, we got into this feeling that val...",George Bush,Vice President,REPUBLICAN,0.000000,-1
...,...,...,...,...,...,...
23528,He has promised a trillion dollars out of the ...,Al Gore,Vice President,DEMOCRAT,0.363438,1
23529,(LAUGHTER) I -- there's an old high school deb...,George W. Bush,Governor,REPUBLICAN,-0.679982,-1
23530,"Well, can I answer that?",George W. Bush,Governor,REPUBLICAN,0.413020,-1
23531,I look forward to the final weeks of this camp...,George W. Bush,Governor,REPUBLICAN,0.625957,-1
23532,"For those of you for me, thanks for your help.",George W. Bush,Governor,REPUBLICAN,0.844495,-1

In [31]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical

ModuleNotFoundError: No module named 'tensorflow'

In [ ]:
df = final_df
df = df[["Text", "Verdict"]].dropna()

# Map labels: -1 → 0, 0 → 1, 1 → 2
label_map = {-1: 0, 0: 1, 1: 2}
df["Verdict"] = df["Verdict"].map(label_map)

texts = df["Text"].astype(str).values
labels = df["Verdict"].values

# One-hot encode
y = to_categorical(labels, num_classes=3)

In [ ]:
MAX_WORDS = 20000
MAX_LEN = 100

tokenizer = Tokenizer(num_words=MAX_WORDS, oov_token="<OOV>")
tokenizer.fit_on_texts(texts)

sequences = tokenizer.texts_to_sequences(texts)
X = pad_sequences(sequences, maxlen=MAX_LEN, padding="post")

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=labels
)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout

In [ ]:
model = Sequential([
    Embedding(MAX_WORDS, 128, input_length=MAX_LEN),
    LSTM(128),
    Dropout(0.5),
    Dense(64, activation="relu"),
    Dropout(0.3),
    Dense(3, activation="softmax")  # 3 classes
])

In [ ]:
model.compile(
    optimizer="adam",
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

model.summary()

In [ ]:
history = model.fit(
    X_train, y_train,
    epochs=5,
    batch_size=64,
    validation_split=0.1
)

In [ ]:
loss, acc = model.evaluate(X_test, y_test)
print("Test Accuracy:", acc)

In [ ]:
reverse_label_map = {0: -1, 1: 0, 2: 1}

def predict_verdict(text):
    seq = tokenizer.texts_to_sequences([text])
    pad = pad_sequences(seq, maxlen=MAX_LEN, padding="post")
    pred = model.predict(pad)
    class_id = np.argmax(pred)
    return reverse_label_map[class_id]